### ISSUE TITLE
Can not download your proposal file

### ISSUE THREAD

**Issue by GavinZhou2014** [daijifeng001/R-FCN#11]
I try to download your proposal file in BaiduYun, [proposal file in baiduyun ](http://pan.baidu.com/s/1nuC8Lhn), but it seems like the link has broken
Upload a new one? Thank you!

**Comment by daijifeng001** [comment]
I just tried and can download it. What is your problem?

**Comment by GavinZhou2014** [comment]
i can't download it! I don't know why, but i can download the other file you provide
