### ISSUE TITLE
Are there pretrained ResNet-18 and ResNet-34 for Caffe?

### ISSUE THREAD

**Issue by caocuong0306** [daijifeng001/R-FCN#13]
Hi @daijifeng001, hi guys

I'm trying R-FCN. However, due to the limit of my GPU card, I need to use smaller net such as resnet-18 and resnet-34.

I want to ask are there pretrained caffe models of resnet-18 and resnet-34? 

I see there are Torch pretrained models of these nets at https://github.com/facebook/fb.resnet.torch/tree/master/pretrained, but I am using Caffe, so please help.

prototxt files are also required.

Thanks,

**Comment by daijifeng001** [comment]
Hi, we do not have such models. Sorry for that.
