### ISSUE TITLE
loading datasets error 

### ISSUE THREAD

**Issue by hongzhangMu** [daijifeng001/R-FCN#15]
Loading dataset...错误使用 textread (line 165)
未找到文件。

出错 imdb_from_voc (line 46)
  imdb.image_ids = textread(sprintf(VOCopts.imgsetpath, image_set), '%s');

出错 Dataset.voc0712_trainval_sp (line 12)
        dataset.imdb_train    = {  imdb_from_voc(devkit2007, 'trainval', '2007', use_flip), ...

出错 script_rfcn_VOC0712_ResNet101_rpn (line 31)
dataset                     = Dataset.voc0712_trainval_sp(dataset, 'train', conf.use_flipped, 'resnet101');

**Comment by argman** [comment]
this is a common errror, when the code says cannot find something, you should place the needed file in the place where the code try to read.

**Comment by zhaow2015** [comment]
How to solve this problem? Where should I find the imdb_voc_2007_trainval file?
Thanks
