### ISSUE TITLE
when i train model this is some errors

### ISSUE THREAD

**Issue by hongzhangMu** [daijifeng001/R-FCN#16]
Hi dai：
错误使用 parpool (line 111)
Failed to start a parallel pool. (For information in addition to the causing error, validate the
profile 'local' in the Cluster Profile Manager.)

出错 new_parpool (line 10)
    p = parpool(number);

出错 rfcn_train (line 94)
    p = new_parpool(1);

出错 script_rfcn_VOC0712_ResNet101_rpn (line 40)
opts.rfcn_model        = rfcn_train(conf, dataset.imdb_train, dataset.roidb_train, ...

原因:
    错误使用 parallel.internal.pool.InteractiveClient/start (line 330)
    Failed to start pool.
        错误使用 parallel.Job/submit (line 304)
        所有维度参数必须大于零

**Comment by daijifeng001** [comment]
It seems that this is a problem of your matlab.

**Comment by chungjin** [comment]
if your matlab version<=2013a, you cannot use these function directly. maybe you should try use matlabpool, or update your matlab version
