### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by kaishijeng** [daijifeng001/R-FCN#2]
Hi, Dai

  I don't have an access of Matlab so it is not possible for me to experiment your code.
 Do you have a plan to convert matlab script to python?

Thanks

**Comment by daijifeng001** [comment]
Hi,

You may make use of the python code of fast rcnn. The interface between caffe and python should be the same in r-fcn and fast rcnn, where the inputs are the image and the rois, and the outputs are the roi scores and bbox regression results.

**Comment by kaishijeng** [comment]
Jifeng

   >>should be the same in r-fcn and fast rcnn
Do you mean I can use python scripts, like tools/demo.py in py-faster-rcnn
to run demo?

Thanks,

**Comment by daijifeng001** [comment]
I am not sure. Maybe you need to make some modifications. But it should not be hard to implement.

**Comment by kaishijeng** [comment]
Thanks,

**Comment by vedrusss** [comment]
Hi guys,

I'm also looking for ways how to avoid matlab usage. I'm trying to use Octave to run .m scripts of R-FCN, but Octave seems doesn't support Cuda (gpuDevice() function is undefined).

Can you help anyway with this issue?

Thanks, Alexey

**Comment by kaishijeng** [comment]
I attempted to create a python version to do test, but no luck due to no experience of MatLab.
The best will be DaiJi so someone  familiar with both Matlb/Python can create a python version to avoid Matlab dependence.

**Comment by daijifeng001** [comment]
We have provided a link to r fcn implementation in Python, thus this issue is solved.
