### ISSUE TITLE
Error when run script_rfcn_VOC0712_ResNet101_OHEM_rpn.m

### ISSUE THREAD

**Issue by leonliuzju** [daijifeng001/R-FCN#20]
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:954] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
```

Could anybody kindly tell me what's wrong with it? thanks a lot.

Besides, What should I do if I want to train R-FCN on my own dataset? I'm confused about how to get the pre-computed region proposals.

**Comment by leonliuzju** [comment]
I've solve the first problem.. It always happens when I run the script on the second time..

**Comment by xiaoxiongli** [comment]
yes, one way to solve this is restart the matlab.

**Comment by duanLH** [comment]
@leonliuzju  How to solve this? I meet the same problem
