### ISSUE TITLE
Error when running  "script_rfcn_demo.m"?

### ISSUE THREAD

**Issue by YingjieYin** [daijifeng001/R-FCN#22]
Hi, when i run the Code  "script_rfcn_demo.m" ,there is the error as follows, (my platform is win64 + matlab2014a)
Invalid MEX-file 'D:\FCN\R-FCN-master\external\caffe\matlab\caffe_rfcn\+caffe\private\caffe_.mexw64': D:\FCN\R-FCN-master\external\caffe\matlab\caffe_rfcn\+caffe\private\caffe_.mexw64 不是有效的 Win32 应用程序。

出错 caffe.set_device (line 9)
caffe_('set_device', device_id);

出错 active_caffe_mex (line 26)
    caffe.set_device(gpu_id-1);

出错 script_rfcn_demo (line 21)
active_caffe_mex(opts.gpu_id, opts.caffe_version);

**Comment by daijifeng001** [comment]
It seems that there is some dependencies for the mex file missing. You may use a dependency walker to check it. I suggest you install VS 2013 first.

**Comment by YingjieYin** [comment]
Thank you very much, the problem has been resolved.
"I put all the ".dll"files in the same file of caffe_.mexw64 "
@daijifeng001

**Comment by ldachuan** [comment]
你好，我也遇到了同样的问题，请问是哪些dll文件放到同一文件夹
