### ISSUE TITLE
Do I need 9 anchors during I implement RPN to generate proposals?

### ISSUE THREAD

**Issue by xiaoxiongli** [daijifeng001/R-FCN#25]
Dear daijifeng:

I want to implement RPN to generate proposals when do the 4-step training(just like faster-rcnn).

I confuse that Do I need the same anchor boxes as faster RCNN? (i.e. 9 anchors [0.5:1,1:1,1:2]x[128 256 512]) ?

**Comment by daijifeng001** [comment]
Hi, yes. Please use the same rpn.

**Comment by xiaoxiongli** [comment]
Dear daijifeng, thank you very much!
