### ISSUE TITLE
do I need add the OHEM layers to the first-stage rpn prototxt

### ISSUE THREAD

**Issue by xiaoxiongli** [daijifeng001/R-FCN#27]
Dear daijifeng:
        when I write the first-stage rpn prototxt,  do I need add the OHEM layers to the first-stage rpn prototxt?    
        (I want use OHEM to do hard examples mining).

By the way, Is it possible to share your rpn prototxt to me? ^_^

**Comment by daijifeng001** [comment]
No, OHEM is not applied to RPN. You can send me an email for the prototxt.

**Comment by twmht** [comment]
@daijifeng001 

why not used ohem for rpn?  rpn also adopts heuristic ways to random pick fg/bg rois for the softmax loss.
