### ISSUE TITLE
about dilate convolution

### ISSUE THREAD

**Issue by 1292765944** [daijifeng001/R-FCN#28]
Dear daijifeng:
       I don't understand why only the res5a_branch2b, res5b_branch2b, res5c_branch2b convolution layer has dilation parameter? what is the point of do that? Thank you!

**Comment by daijifeng001** [comment]
Because we removed downsampling between conv4 and conv5, so as to set the output feature stride to 16 instead of 32. Adding dilation can ensure the receptive field of conv5 does not reduce due to the removal.
