### ISSUE TITLE
cant download file in fetch_data from dropbox or BaiduYun

### ISSUE THREAD

**Issue by jhihyiwu** [daijifeng001/R-FCN#29]
I run all .m file in fetch_data folder and there is the same error  "Error in downloading, please try links in README.md https://github.com/daijifeng001/R-FCN"

I open the matlab and found the dropbox account .  The message in the dropbox account is "This account's links are generating too much traffic and have been temporarily disabled!"

I download from BaiduYun cloud but the zip file is broken .

Is there problem of dropbox account or just the compiler processing in matlab  going wrong?

Thank for helping

**Comment by daijifeng001** [comment]
Hi,

Sorry for the inconvenience. We are working to solve the problem.

**Comment by daijifeng001** [comment]
Problem solved!
