### ISSUE TITLE
why the bbox_targets has 8 dim not 4?

### ISSUE THREAD

**Issue by vzvzx** [daijifeng001/R-FCN#30]
why the bbox_targets have 8 dim, not 4?
and the begin 4 dim is all 0?

**Comment by daijifeng001** [comment]
The first 4 dims are for the null category, and is not used.

**Comment by hongjo** [comment]
The two classes-background and foreground-exist in the layer of class agnostic bbox regression. As mentioned by @daijifeng001, the background class is actually not used.
