### ISSUE TITLE
How to generate .mat file in demo image?

### ISSUE THREAD

**Issue by jhihyiwu** [daijifeng001/R-FCN#38]
I found that each demo image in demo folder has its own .mat but i dont know how to generate .mat for other image.

I want to testing other image using "script_rfcn_demo" .
 
How to generate .mat file for other image ? Dose .mat file generate from training processing ?

I use demo .mat file to testing other image (not demo image) and it can be tested .Is that accurancy for testing ? 

Thanks.

**Comment by daijifeng001** [comment]
Hi, please check the paper. R-FCN utilizes region proposals pre-generated. You need to derive the region proposals on the image.
