### ISSUE TITLE
运行script_rfcn_demo.m时出现错误，matlab崩溃

### ISSUE THREAD

**Issue by fangyuanandwei** [daijifeng001/R-FCN#45]
你好！感谢分享！运行script_rfcn_demo.m时出现错误，matlab崩溃。
我使用的是MATLAB 2015b，GTX770（2G）
请问可能的错误是什么？
请问运行script_rfcn_demo.m时需要更大的内存，显存吗？

**Comment by northeastsquare** [comment]
应该不够吧，你看一下linux command line 打印的错误

**Comment by zhangjunior** [comment]
我也是出现崩溃的情况，运行到scale layer的reshape出错，net初始化时候根据prototxt文件建立了一个blob大小，但是检测时应该是根据输入图片大小reshape。这里的scale layer和caffe原版有一些不同，在scale_layer.cpp的91行。所以导致temp_ reshape没有执行，后面的caffe copy就崩溃了。

请大神解答一下啊！

**Comment by liyi14** [comment]
@zhangjunior 你好，感谢您指出这个bug。
当时修改是为了优化scale_layer的显存占用。在forward_cpu中出现这个bug是我们的疏忽，会尽快修复这个bug。
不过出现崩溃的情况应该是因为显存不够，你们可以通过更换显存更大的GPU或者实现PSRoIPooling的Forward_cpu来解决（可以参考roi_pooling_layer的Forward_cpu是怎么移植Forward_gpu的，需要改动的地方很少，我们之后也会更新这部分）。

**Comment by zhangjunior** [comment]
@liyi14 非常感谢！
