### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by fujihuang** [daijifeng001/R-FCN#53]
Hi ,  when i try to run 'experiments/script_rfcn_demo.m',i encounter this problem:
Warning: Specified caffe folder (/home/siahooar/Downloads/r-fcn/experiments/external/caffe/matlab/caffe_rfcn) is not exist,
change to default one (/home/siahooar/Downloads/r-fcn/experiments/external/caffe/matlab) 
> In active_caffe_mex (line 19)
  In script_rfcn_demo (line 21) 
Error using cd
Cannot CD to /home/siahooar/Downloads/r-fcn/experiments/external/caffe/matlab (Name is nonexistent or not a directory).

and i have browse these code i found that there is a 'pwd', so when i run this code,it just means that path=/home/siahooar/Downloads/r-fcn/experiments,so this directory(caffe) is unable to be exsited~and why use pwd,then the path is not r-fcn but r-fcn/experiments.
Are there anyone had encountered this problem too?Please let me know i did not miss anything~ Thx

**Comment by fujihuang** [comment]
@daijifeng001

**Comment by fujihuang** [comment]
i have solved this problem,i modified this code,i did not use " pwd " anymore,i try to assign the path

**Comment by fbi0817** [comment]
I meet the same problem like yours @fujihuang , since the /external/caffe/matlab is in /R-FCN/ not in /R-FCN/experiment, and I havn't solved the problem, can anyone help?THX @daijifeng001

**Comment by fbi0817** [comment]
just then ,i can run the code successfully. You should make sure your current directory in the matlab (above the code part) is /R-FCN not in /R-FCN/experiments , and then click the experiments/ and run the .m  file @fujihuang

**Comment by fujihuang** [comment]
THX,and i have solved this too,i just wonder how many people have encountered this problem~

**Comment by ujsyehao** [comment]
@fbi0817 Thank you, your method solved it and it confused me for 12 hours!
