### ISSUE TITLE
Error using roidb_from_voc:roidb_from_ilsvrc:: cannot find ./data/self_proposal_data/voc_2007_trainval_resnet101.mat

### ISSUE THREAD

**Issue by fbi0817** [daijifeng001/R-FCN#56]
I put the voc2007 and voc2012 correctly, and run the /home/jiwei/Downloads/R-FCN/experiments/script_rfcn_VOC0712_ResNet101_OHEM_rpn.m file
I got the error like this:

Error using roidb_from_voc (line 58)
roidb_from_ilsvrc:: cannot find ./data/self_proposal_data/voc_2007_trainval_resnet101.mat

Error in
Dataset.voc0712_trainval_sp>@(x)x.roidb_func(x,'with_self_proposal',true,'extension',extension)
(line 14)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, 'with_self_proposal', true,
        'extension', extension), dataset.imdb_train, 'UniformOutput', false);

Error in Dataset.voc0712_trainval_sp (line 14)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, 'with_self_proposal', true,
        'extension', extension), dataset.imdb_train, 'UniformOutput', false);

Error in script_rfcn_VOC0712_ResNet101_OHEM_rpn (line 31)
dataset                     = Dataset.voc0712_trainval_sp(dataset, 'train', conf.use_flipped,
'resnet101');

and I don't know where to create the  ./data/self_proposal_data/voc_2007_trainval_resnet101.mat file , can anyone help me? Thank you

**Comment by liyi14** [comment]
In `Preparation for Training & Testing`
> 4. Run fetch_data/fetch_region_proposals.m to download the pre-computed region proposals.

**Comment by fbi0817** [comment]
Oh ,thank you @liyi14  ,it's my fault, I skip the instruction
